name: CI

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
